# Generated by Django 5.1.4 on 2025-04-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_collection", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sixmonthdata",
            name="loan_source_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cla", "CLA"),
                    ("micro_finance", "Micro-finance"),
                    ("bank", "Bank"),
                    ("local_money_lenders", "Local Money Lenders"),
                    ("others", "Others"),
                    ("no_loan_from_other_source", "No Loan From Other Source"),
                ],
                max_length=50,
                null=True,
                verbose_name="Source (Code)",
            ),
        ),
    ]
