# Generated by Django 5.1.4 on 2025-05-03 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cluster_management", "0001_initial"),
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cluster",
            name="cluster_manager",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coordinated_clusters",
                to="user_management.weemaentities",
            ),
        ),
        migrations.AddField(
            model_name="selfhelpgroup",
            name="cluster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="cluster_management.cluster",
            ),
        ),
        migrations.AddField(
            model_name="selfhelpgroup",
            name="facilitator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="facilitated_groups",
                to="user_management.weemaentities",
            ),
        ),
        migrations.AddField(
            model_name="selfhelpgroup",
            name="group_leader",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="led_groups",
                to="user_management.weemaentities",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="cluster_management.selfhelpgroup",
            ),
        ),
    ]
