# Generated by Django 5.1.4 on 2025-05-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name="selfhelpgroup",
            name="group_creation_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
